minimumReleaseAgeExclude:
  - '@nuxt/cli-nightly@4.0.0-20260824-125839-d3213ce'
  - fontless@0.4.2

packages:
  - docs
  - playground
  - proxy

overrides:
  '@nuxt/cli': 'npm:@nuxt/cli-nightly@4.0.0-20260829-200936-84e7673'
  ofetch: ^2.0.0-alpha.3
  unifont: 'link:.'

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: true
  simple-git-hooks: true
  unrs-resolver: false
