minimumReleaseAgeExclude:
  - '@nuxt/cli-nightly@4.0.0-20260824-125839-d3213ce'
  - fontless@1.0.0
  - airspace@0.1.6
  - fontaine@1.0.0

packages:
  - docs
  - playground
  - proxy

overrides:
  '@nuxt/cli': 'npm:@nuxt/cli-nightly@4.0.0-20260920-212707-4d81025'
  ofetch: ^2.0.0-alpha.3
  unifont: 'link:.'

allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  sharp: true
  simple-git-hooks: true
  unrs-resolver: false
